---
- name: install vim
  apt:
    name: vim
    state: present
- name: install ripgrep
  apt:
    name: ripgrep
    state: present
- name: install iftop
  apt:
    name: iftop
    state: present
- name: install nload
  apt:
    name: nload
    state: present
